# Generated by Django 5.2.7 on 2025-10-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.SlugField(max_length=120, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=120)),
                ('country_flag', models.CharField(blank=True, max_length=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sdg_score', models.PositiveIntegerField(default=0)),
                ('thumb', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('info_company', models.CharField(blank=True, max_length=255, null=True)),
                ('info_address', models.CharField(blank=True, max_length=512, null=True)),
                ('info_website', models.URLField(blank=True, null=True)),
                ('info_blockchain', models.CharField(blank=True, max_length=255, null=True)),
                ('info_type', models.CharField(blank=True, max_length=255, null=True)),
                ('info_mechanism', models.CharField(blank=True, max_length=255, null=True)),
                ('info_characteristics', models.CharField(blank=True, max_length=255, null=True)),
                ('info_registry', models.CharField(blank=True, max_length=255, null=True)),
                ('info_registry_url', models.URLField(blank=True, null=True)),
                ('info_validator', models.CharField(blank=True, max_length=255, null=True)),
                ('info_status', models.CharField(blank=True, max_length=120, null=True)),
                ('info_credit_start', models.CharField(blank=True, max_length=120, null=True)),
                ('info_credit_end', models.CharField(blank=True, max_length=120, null=True)),
                ('sdgs_csv', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.IntegerField()),
                ('date', models.CharField(max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Vintage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('volume', models.BigIntegerField()),
                ('unit', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vintages', to='projects.project')),
            ],
        ),
    ]
